name: Publish

on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.gitignore'
     - 'CONTRIBUTING.md'
     - 'LICENSE'
     - 'README.md'
     - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
        # https://github.com/gradle/actions for documentation
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build Project
        run: ./gradlew build

      # https://cli.github.com/manual/gh_release_create
      - name: Create release
        run: gh release create draft build/libs/DCIFileReader-*.jar --draft --latest --notes "https://github.com/${{github.repository}}/commit/${{github.sha}} https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}