name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    paths-ignore:
    - '.gitignore'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'README.md'
    - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
        # https://github.com/gradle/actions for documentation
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build Project with Gradle
        run: ./gradlew build
        # print github project version to an environment variable.
      - name: Print project version from build.gradle
        run: echo "VERSION_INFORMATION=$(${{github.workspace}}/gradlew -q printVersion)" >> $GITHUB_ENV
      - name: Archive Artifacts to Action.
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: DCIFileReader-${{ env.VERSION_INFORMATION }}
          path: build/libs/DCIFileReader-*.jar
      # https://cli.github.com/manual/gh_release_create
      - name: Create release
        run: gh release create ${{ env.VERSION_INFORMATION }} build/libs/DCIFileReader-*.jar --draft --latest --title ${{ env.VERSION_INFORMATION }} --notes "**Full Changelog:** https://github.com/${{github.repository}}/commit/${{github.sha}} --- [Action Run & Artifacts](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}