name: Publish

on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.gitignore'
     - 'CONTRIBUTING.md'
     - 'LICENSE'
     - 'README.md'
     - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
        # https://github.com/gradle/actions for documentation
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Build Project
        run: ./gradlew build
        # Delete releases that only have the tag "pre-release" when build is successful
        # https://cli.github.com/manual/gh_release_delete
      - run: gh release delete draft --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Before setting this as a release, you must manually delete the current release and then tag.
      # https://cli.github.com/manual/gh_release_create
      - name: Create release
        run: gh release create draft build/libs/DCIFileReader-*.jar --draft --latest --notes >
          "https://github.com/${{github.repository}}/compare/${{github.sha}}...master"
          "https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}