name: Publish

on:
  workflow_dispatch:
  push:
   paths-ignore:
     - '.gitignore'
     - 'CONTRIBUTING.md'
     - 'LICENSE'
     - 'README.md'
     - 'licenseheader.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@72f2cec99f417b1a1c5e2e88945068983b7965f9
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4
      - uses: actions/setup-java@4075bfc1b51bf22876335ae1cd589602d60d8758
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build Project
        run: ./gradlew build
	#Using this to delete releases that only have the tag "release" when build is successful
      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: pre-release #(required) tag name to delete 
          delete_release: true #(optional) default: true 
          #repo: <owner>/<repoName> #(optional) target repository. default: repo running this action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://stackoverflow.com/a/73692692 
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
	  artifacts: build/libs/DCIFileReader-*.jar
          body: > 
"https://github.com/${{github.repository}}/compare/${{github.sha}}...master"
"https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"
          draft: true
	  generateReleaseNotes: true
          prerelease: true
          tag: "pre-release"
          token: ${{ secrets.GITHUB_TOKEN }}